//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace SAP.DataModel
{
  public class sentiment
  {
    public sentiment() => this.sentiment_sentences = (ICollection<SAP.DataModel.sentiment_sentences>) new HashSet<SAP.DataModel.sentiment_sentences>();

    public int id { get; set; }

    public DateTime date_created { get; set; }

    public Decimal? average_score { get; set; }

    public int sentiment_queue_id { get; set; }

    public virtual ICollection<SAP.DataModel.sentiment_sentences> sentiment_sentences { get; set; }

    public virtual sentiment_queue sentiment_queue { get; set; }
  }
}
