//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace SAP.DataModel
{    
    public class sentiment_queue
    {
        public sentiment_queue()
        {
            this.sentiment_queue_error = (ICollection<SAP.DataModel.sentiment_queue_error>)new HashSet<SAP.DataModel.sentiment_queue_error>();
            this.sentiments = (ICollection<sentiment>)new HashSet<sentiment>();
        }
    
        public int id { get; set; }
        public string text_for_analysis { get; set; }
        public DateTime? date_created { get; set; }
        public int? batch_id { get; set; }
        public bool processed { get; set; }
        public DateTime? date_processed { get; set; }
        public bool? error { get; set; }

        public virtual sentiment_batch sentiment_batch { get; set; }
        public virtual ICollection<SAP.DataModel.sentiment_queue_error> sentiment_queue_error { get; set; }
        public virtual ICollection<sentiment> sentiments { get; set; }
    }
}
